name: Test Deployment Secrets

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  contents: read

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test Coolify webhook accessibility
        run: |
          echo "🔍 Testing Coolify webhook configuration..."
          
          # Test if webhook URL is accessible (without sending actual request)
          if curl -I "$COOLIFY_WEBHOOK" --connect-timeout 10 --max-time 30; then
            echo "✅ Webhook URL is reachable"
          else
            echo "❌ Webhook URL is not reachable or returned error"
            exit 1
          fi
          
          # Validate URL format (basic check)
          if [[ "$COOLIFY_WEBHOOK" == *"coolify"* ]]; then
            echo "✅ Webhook URL contains 'coolify'"
          else
            echo "❌ Webhook URL doesn't seem to be a Coolify URL"
            exit 1
          fi
          
          # Test token is not empty
          if [ -n "$COOLIFY_TOKEN" ]; then
            echo "✅ Coolify token is configured"
            echo "Token length: ${#COOLIFY_TOKEN} characters"
          else
            echo "❌ Coolify token is empty"
            exit 1
          fi
          
          echo "🎉 Secret validation completed successfully!"
        env:
          COOLIFY_WEBHOOK: ${{ secrets.COOLIFY_WEBHOOK }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}